create table if not exists lecture (
    id bigint generated by default as identity,
    name varchar(255),
    title varchar(255),
    primary key (id)
);
create table if not exists attachment (
    id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    lecture_id bigint,
    primary key (id),
    foreign key (lecture_id) references lecture
);

create table if not exists comment (
    id bigint generated by default as identity,
    name varchar(255),
    comment varchar(255),
    lecture_id bigint,
    primary key (id),
    foreign key (lecture_id) references lecture
);

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    full_Name VARCHAR(50),
    email VARCHAR(50),
    phone VARCHAR(50),
    PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
);